import { FoodItem } from '../types';

export const INDIAN_FOOD_DATABASE: FoodItem[] = [
  // --- SOUTH INDIAN ---
  { id: 'f-1', name: 'Plain Dosa', calories: 120, protein: 3, carbs: 22, fat: 3, servingSize: '1 Dosa (80g)', category: 'South Indian' },
  { id: 'f-2', name: 'Masala Dosa', calories: 250, protein: 5, carbs: 40, fat: 8, servingSize: '1 Dosa (150g)', category: 'South Indian' },
  { id: 'f-3', name: 'Idli', calories: 65, protein: 2, carbs: 12, fat: 0.5, servingSize: '1 Piece (50g)', category: 'South Indian' },
  { id: 'f-4', name: 'Medu Vada', calories: 180, protein: 4, carbs: 18, fat: 10, servingSize: '1 Piece (60g)', category: 'South Indian' },
  { id: 'f-5', name: 'Rava Dosa', calories: 180, protein: 3, carbs: 28, fat: 6, servingSize: '1 Dosa (100g)', category: 'South Indian' },
  { id: 'f-6', name: 'Onion Uttapam', calories: 220, protein: 5, carbs: 36, fat: 6, servingSize: '1 Piece (140g)', category: 'South Indian' },
  { id: 'f-7', name: 'Upma', calories: 190, protein: 4, carbs: 32, fat: 5, servingSize: '1 Bowl (150g)', category: 'South Indian' },
  { id: 'f-8', name: 'Ven Pongal', calories: 240, protein: 6, carbs: 38, fat: 7, servingSize: '1 Bowl (180g)', category: 'South Indian' },
  { id: 'f-9', name: 'Appam', calories: 100, protein: 2, carbs: 20, fat: 1.5, servingSize: '1 Piece (60g)', category: 'South Indian' },
  { id: 'f-10', name: 'Putu / Pittu', calories: 150, protein: 3, carbs: 30, fat: 2, servingSize: '1 Piece (100g)', category: 'South Indian' },
  { id: 'f-11', name: 'Sambar', calories: 85, protein: 4, carbs: 14, fat: 1.5, servingSize: '1 Katori (150ml)', category: 'South Indian' },
  { id: 'f-12', name: 'Rasam', calories: 40, protein: 1, carbs: 7, fat: 1, servingSize: '1 Katori (150ml)', category: 'South Indian' },
  { id: 'f-13', name: 'Curd Rice', calories: 210, protein: 5, carbs: 32, fat: 7, servingSize: '1 Bowl (200g)', category: 'South Indian' },
  { id: 'f-14', name: 'Lemon Rice', calories: 230, protein: 4, carbs: 42, fat: 5, servingSize: '1 Bowl (180g)', category: 'South Indian' },
  { id: 'f-15', name: 'Tamarind Rice (Puliyogare)', calories: 260, protein: 4, carbs: 46, fat: 7, servingSize: '1 Bowl (180g)', category: 'South Indian' },
  { id: 'f-16', name: 'Chicken Chettinad', calories: 320, protein: 28, carbs: 8, fat: 20, servingSize: '1 Katori (200g)', category: 'South Indian' },
  { id: 'f-17', name: 'Chicken Sukka', calories: 290, protein: 30, carbs: 6, fat: 16, servingSize: '1 Bowl (180g)', category: 'South Indian' },
  { id: 'f-18', name: 'Fish Curry (Nadan / South Style)', calories: 220, protein: 22, carbs: 6, fat: 12, servingSize: '1 Katori (200g)', category: 'South Indian' },
  { id: 'f-19', name: 'Avial', calories: 140, protein: 3, carbs: 15, fat: 8, servingSize: '1 Katori (150g)', category: 'South Indian' },
  { id: 'f-20', name: 'Kuzhi Paniyaram (5 pcs)', calories: 170, protein: 4, carbs: 28, fat: 5, servingSize: '5 Pieces (100g)', category: 'South Indian' },

  // --- NORTH INDIAN ---
  { id: 'f-21', name: 'Chapati / Roti', calories: 80, protein: 3, carbs: 15, fat: 1, servingSize: '1 Medium (35g)', category: 'North Indian' },
  { id: 'f-22', name: 'Butter Naan', calories: 260, protein: 6, carbs: 42, fat: 8, servingSize: '1 Piece (90g)', category: 'North Indian' },
  { id: 'f-23', name: 'Aloo Paratha', calories: 290, protein: 6, carbs: 45, fat: 10, servingSize: '1 Paratha (140g)', category: 'North Indian' },
  { id: 'f-24', name: 'Paneer Paratha', calories: 340, protein: 12, carbs: 40, fat: 15, servingSize: '1 Paratha (150g)', category: 'North Indian' },
  { id: 'f-25', name: 'Methi Paratha', calories: 210, protein: 5, carbs: 32, fat: 7, servingSize: '1 Paratha (110g)', category: 'North Indian' },
  { id: 'f-26', name: 'Puri (2 pcs)', calories: 220, protein: 4, carbs: 26, fat: 11, servingSize: '2 Pieces (70g)', category: 'North Indian' },
  { id: 'f-27', name: 'Chole Bhature', calories: 480, protein: 12, carbs: 65, fat: 20, servingSize: '1 Bhatura + Chole (250g)', category: 'North Indian' },
  { id: 'f-28', name: 'Dal Tadka', calories: 150, protein: 7, carbs: 20, fat: 5, servingSize: '1 Katori (180g)', category: 'North Indian' },
  { id: 'f-29', name: 'Dal Makhani', calories: 260, protein: 9, carbs: 24, fat: 14, servingSize: '1 Katori (180g)', category: 'North Indian' },
  { id: 'f-30', name: 'Paneer Butter Masala', calories: 320, protein: 11, carbs: 14, fat: 24, servingSize: '1 Katori (200g)', category: 'North Indian' },
  { id: 'f-31', name: 'Kadai Paneer', calories: 280, protein: 12, carbs: 10, fat: 21, servingSize: '1 Katori (200g)', category: 'North Indian' },
  { id: 'f-32', name: 'Palak Paneer', calories: 240, protein: 11, carbs: 8, fat: 18, servingSize: '1 Katori (200g)', category: 'North Indian' },
  { id: 'f-33', name: 'Rajma Masala', calories: 180, protein: 8, carbs: 28, fat: 4, servingSize: '1 Katori (180g)', category: 'North Indian' },
  { id: 'f-34', name: 'Chana Masala', calories: 170, protein: 7, carbs: 26, fat: 4.5, servingSize: '1 Katori (180g)', category: 'North Indian' },
  { id: 'f-35', name: 'Butter Chicken', calories: 380, protein: 26, carbs: 12, fat: 25, servingSize: '1 Katori (220g)', category: 'North Indian' },
  { id: 'f-36', name: 'Chicken Tikka Masala', calories: 330, protein: 28, carbs: 10, fat: 20, servingSize: '1 Katori (200g)', category: 'North Indian' },
  { id: 'f-37', name: 'Kadai Chicken', calories: 290, protein: 27, carbs: 8, fat: 17, servingSize: '1 Katori (200g)', category: 'North Indian' },
  { id: 'f-38', name: 'Aloo Gobi', calories: 130, protein: 3, carbs: 18, fat: 5, servingSize: '1 Katori (150g)', category: 'North Indian' },
  { id: 'f-39', name: 'Bhindi Masala', calories: 110, protein: 3, carbs: 12, fat: 6, servingSize: '1 Katori (150g)', category: 'North Indian' },
  { id: 'f-40', name: 'Shahi Paneer', calories: 310, protein: 10, carbs: 16, fat: 23, servingSize: '1 Katori (200g)', category: 'North Indian' },

  // --- RICE VARIETIES ---
  { id: 'f-41', name: 'Steamed White Rice', calories: 180, protein: 3.5, carbs: 40, fat: 0.5, servingSize: '1 Bowl (150g)', category: 'Rice' },
  { id: 'f-42', name: 'Brown Rice', calories: 160, protein: 4, carbs: 34, fat: 1.5, servingSize: '1 Bowl (150g)', category: 'Rice' },
  { id: 'f-43', name: 'Jeera Rice', calories: 210, protein: 4, carbs: 41, fat: 3.5, servingSize: '1 Bowl (160g)', category: 'Rice' },
  { id: 'f-44', name: 'Vegetable Biryani', calories: 290, protein: 6, carbs: 50, fat: 8, servingSize: '1 Plate (250g)', category: 'Rice' },
  { id: 'f-45', name: 'Chicken Biryani', calories: 420, protein: 24, carbs: 52, fat: 14, servingSize: '1 Plate (300g)', category: 'Rice' },
  { id: 'f-46', name: 'Mutton Biryani', calories: 490, protein: 22, carbs: 50, fat: 22, servingSize: '1 Plate (300g)', category: 'Rice' },
  { id: 'f-47', name: 'Egg Biryani', calories: 360, protein: 14, carbs: 48, fat: 12, servingSize: '1 Plate (280g)', category: 'Rice' },
  { id: 'f-48', name: 'Khichdi (Dal & Rice)', calories: 190, protein: 6, carbs: 35, fat: 3, servingSize: '1 Bowl (200g)', category: 'Rice' },
  { id: 'f-49', name: 'Vegetable Pulao', calories: 220, protein: 4.5, carbs: 42, fat: 4, servingSize: '1 Bowl (180g)', category: 'Rice' },
  { id: 'f-50', name: 'Veg Fried Rice', calories: 280, protein: 5, carbs: 46, fat: 9, servingSize: '1 Plate (220g)', category: 'Rice' },
  { id: 'f-51', name: 'Egg Fried Rice', calories: 340, protein: 12, carbs: 45, fat: 12, servingSize: '1 Plate (250g)', category: 'Rice' },
  { id: 'f-52', name: 'Chicken Fried Rice', calories: 380, protein: 20, carbs: 44, fat: 14, servingSize: '1 Plate (260g)', category: 'Rice' },

  // --- BREAKFAST SPECIALS ---
  { id: 'f-53', name: 'Poha', calories: 180, protein: 3, carbs: 33, fat: 4, servingSize: '1 Bowl (150g)', category: 'Breakfast' },
  { id: 'f-54', name: 'Besan Chilla', calories: 150, protein: 7, carbs: 18, fat: 5, servingSize: '1 Chilla (80g)', category: 'Breakfast' },
  { id: 'f-55', name: 'Oats in Milk', calories: 230, protein: 10, carbs: 36, fat: 5, servingSize: '1 Bowl (250ml)', category: 'Breakfast' },
  { id: 'f-56', name: 'Oats Upma', calories: 170, protein: 5, carbs: 28, fat: 4, servingSize: '1 Bowl (150g)', category: 'Breakfast' },
  { id: 'f-57', name: 'Moong Dal Chilla', calories: 140, protein: 8, carbs: 20, fat: 3, servingSize: '1 Chilla (80g)', category: 'Breakfast' },
  { id: 'f-58', name: 'Thepla (2 pcs)', calories: 220, protein: 5, carbs: 30, fat: 9, servingSize: '2 Pieces (80g)', category: 'Breakfast' },
  { id: 'f-59', name: 'Sabudana Khichdi', calories: 270, protein: 3, carbs: 48, fat: 8, servingSize: '1 Bowl (160g)', category: 'Breakfast' },
  { id: 'f-60', name: 'Bread Omelette (2 eggs)', calories: 310, protein: 16, carbs: 24, fat: 16, servingSize: '2 Slices + 2 Eggs', category: 'Breakfast' },
  { id: 'f-61', name: 'Boiled Egg Whites (4 pcs)', calories: 68, protein: 14, carbs: 1, fat: 0.2, servingSize: '4 Egg Whites (130g)', category: 'Breakfast' },
  { id: 'f-62', name: 'Whole Boiled Eggs (2 pcs)', calories: 150, protein: 13, carbs: 1, fat: 10, servingSize: '2 Eggs (100g)', category: 'Breakfast' },

  // --- HIGH PROTEIN FOODS ---
  { id: 'f-63', name: 'Grilled Chicken Breast', calories: 165, protein: 31, carbs: 0, fat: 3.6, servingSize: '1 Piece (100g)', category: 'Protein' },
  { id: 'f-64', name: 'Boiled Chicken Breast', calories: 150, protein: 30, carbs: 0, fat: 3, servingSize: '100g', category: 'Protein' },
  { id: 'f-65', name: 'Whey Protein Scoop (1 Scoop)', calories: 120, protein: 24, carbs: 2, fat: 1.5, servingSize: '1 Scoop (30g)', category: 'Protein' },
  { id: 'f-66', name: 'Raw Paneer', calories: 265, protein: 18, carbs: 6, fat: 20, servingSize: '100g', category: 'Protein' },
  { id: 'f-67', name: 'Low Fat Paneer', calories: 180, protein: 22, carbs: 4, fat: 8, servingSize: '100g', category: 'Protein' },
  { id: 'f-68', name: 'Soya Chunks (Cooked)', calories: 170, protein: 26, carbs: 14, fat: 0.5, servingSize: '1 Bowl (150g)', category: 'Protein' },
  { id: 'f-69', name: 'Tofu (Soya Paneer)', calories: 140, protein: 15, carbs: 3, fat: 8, servingSize: '100g', category: 'Protein' },
  { id: 'f-70', name: 'Sprouted Moong Salad', calories: 120, protein: 8, carbs: 20, fat: 1, servingSize: '1 Bowl (150g)', category: 'Protein' },
  { id: 'f-71', name: 'Greek Yogurt (Plain)', calories: 95, protein: 10, carbs: 5, fat: 4, servingSize: '1 Cup (150g)', category: 'Protein' },
  { id: 'f-72', name: 'Fish Fillet (Grilled)', calories: 180, protein: 24, carbs: 0, fat: 8, servingSize: '100g', category: 'Protein' },
  { id: 'f-73', name: 'Roasted Chana', calories: 160, protein: 9, carbs: 22, fat: 3, servingSize: '1 Handful (40g)', category: 'Protein' },
  { id: 'f-74', name: 'Peanut Butter', calories: 190, protein: 8, carbs: 6, fat: 16, servingSize: '2 tbsp (32g)', category: 'Protein' },

  // --- VEGETABLES & SALADS ---
  { id: 'f-75', name: 'Green Salad Mix', calories: 35, protein: 1.5, carbs: 7, fat: 0.2, servingSize: '1 Large Bowl (150g)', category: 'Vegetable' },
  { id: 'f-76', name: 'Cucumber Slices', calories: 16, protein: 0.7, carbs: 3.8, fat: 0.1, servingSize: '1 Medium (100g)', category: 'Vegetable' },
  { id: 'f-77', name: 'Mix Veg Sabzi', calories: 120, protein: 3, carbs: 14, fat: 6, servingSize: '1 Katori (150g)', category: 'Vegetable' },
  { id: 'f-78', name: 'Spinach / Palak Sabzi', calories: 90, protein: 3.5, carbs: 8, fat: 5, servingSize: '1 Katori (150g)', category: 'Vegetable' },
  { id: 'f-79', name: 'Baingan Bharta', calories: 110, protein: 2, carbs: 12, fat: 6, servingSize: '1 Katori (150g)', category: 'Vegetable' },
  { id: 'f-80', name: 'Lauki (Bottle Gourd) Sabzi', calories: 70, protein: 1.5, carbs: 8, fat: 3.5, servingSize: '1 Katori (150g)', category: 'Vegetable' },
  { id: 'f-81', name: 'Cabbage Poriyal / Sabzi', calories: 85, protein: 2, carbs: 10, fat: 4, servingSize: '1 Katori (150g)', category: 'Vegetable' },
  { id: 'f-82', name: 'Mushroom Masala', calories: 130, protein: 5, carbs: 9, fat: 8, servingSize: '1 Katori (150g)', category: 'Vegetable' },
  { id: 'f-83', name: 'Beetroot Poriyal', calories: 95, protein: 2, carbs: 16, fat: 3, servingSize: '1 Katori (150g)', category: 'Vegetable' },

  // --- FRUITS & NUTS ---
  { id: 'f-84', name: 'Banana', calories: 105, protein: 1.3, carbs: 27, fat: 0.3, servingSize: '1 Medium (118g)', category: 'Fruit' },
  { id: 'f-85', name: 'Apple', calories: 95, protein: 0.5, carbs: 25, fat: 0.3, servingSize: '1 Medium (182g)', category: 'Fruit' },
  { id: 'f-86', name: 'Mango Slices', calories: 130, protein: 1, carbs: 32, fat: 0.5, servingSize: '1 Cup (165g)', category: 'Fruit' },
  { id: 'f-87', name: 'Papaya Cubes', calories: 60, protein: 0.9, carbs: 15, fat: 0.4, servingSize: '1 Bowl (140g)', category: 'Fruit' },
  { id: 'f-88', name: 'Guava', calories: 68, protein: 2.6, carbs: 14, fat: 1, servingSize: '1 Medium (100g)', category: 'Fruit' },
  { id: 'f-89', name: 'Orange', calories: 62, protein: 1.2, carbs: 15, fat: 0.2, servingSize: '1 Medium (130g)', category: 'Fruit' },
  { id: 'f-90', name: 'Watermelon Cubes', calories: 46, protein: 0.9, carbs: 11, fat: 0.2, servingSize: '1 Bowl (150g)', category: 'Fruit' },
  { id: 'f-91', name: 'Pomegranate Seeds', calories: 110, protein: 2.2, carbs: 24, fat: 1.5, servingSize: '1 Bowl (130g)', category: 'Fruit' },
  { id: 'f-92', name: 'Chikoo (Sapodilla)', calories: 83, protein: 0.4, carbs: 20, fat: 1.1, servingSize: '1 Medium (100g)', category: 'Fruit' },
  { id: 'f-93', name: 'Green Grapes', calories: 70, protein: 0.7, carbs: 18, fat: 0.2, servingSize: '1 Cup (100g)', category: 'Fruit' },
  { id: 'f-94', name: 'Almonds', calories: 160, protein: 6, carbs: 6, fat: 14, servingSize: 'Handful (28g / ~23 nuts)', category: 'Fruit' },
  { id: 'f-95', name: 'Walnuts', calories: 185, protein: 4.3, carbs: 3.9, fat: 18.5, servingSize: 'Handful (28g / ~14 halves)', category: 'Fruit' },
  { id: 'f-96', name: 'Dates (Khajoor)', calories: 133, protein: 1.2, carbs: 36, fat: 0.2, servingSize: '4 Pieces (50g)', category: 'Fruit' },

  // --- DRINKS & BEVERAGES ---
  { id: 'f-97', name: 'Indian Masala Chai (With Milk & Sugar)', calories: 90, protein: 2.5, carbs: 12, fat: 3, servingSize: '1 Small Cup (150ml)', category: 'Drink' },
  { id: 'f-98', name: 'Black Coffee (No Sugar)', calories: 5, protein: 0.3, carbs: 0, fat: 0, servingSize: '1 Cup (200ml)', category: 'Drink' },
  { id: 'f-99', name: 'South Indian Filter Coffee', calories: 110, protein: 3, carbs: 14, fat: 4, servingSize: '1 Cup (150ml)', category: 'Drink' },
  { id: 'f-100', name: 'Sweet Lassi', calories: 220, protein: 6, carbs: 32, fat: 8, servingSize: '1 Glass (250ml)', category: 'Drink' },
  { id: 'f-101', name: 'Salted Buttermilk / Chaas', calories: 45, protein: 2, carbs: 4, fat: 2, servingSize: '1 Glass (250ml)', category: 'Drink' },
  { id: 'f-102', name: 'Tender Coconut Water', calories: 45, protein: 1, carbs: 10, fat: 0.5, servingSize: '1 Coconut (250ml)', category: 'Drink' },
  { id: 'f-103', name: 'Sugarcane Juice', calories: 180, protein: 0.5, carbs: 45, fat: 0, servingSize: '1 Glass (250ml)', category: 'Drink' },
  { id: 'f-104', name: 'Badam Milk', calories: 210, protein: 7, carbs: 24, fat: 9, servingSize: '1 Glass (200ml)', category: 'Drink' },
  { id: 'f-105', name: 'Green Tea (No Sugar)', calories: 2, protein: 0, carbs: 0.5, fat: 0, servingSize: '1 Cup (200ml)', category: 'Drink' },
  { id: 'f-106', name: 'Fresh Lime Soda (Sweet & Salt)', calories: 80, protein: 0.2, carbs: 20, fat: 0, servingSize: '1 Glass (250ml)', category: 'Drink' },

  // --- SNACKS ---
  { id: 'f-107', name: 'Samosa', calories: 250, protein: 4, carbs: 32, fat: 12, servingSize: '1 Piece (90g)', category: 'Snack' },
  { id: 'f-108', name: 'Dhokla', calories: 150, protein: 5, carbs: 22, fat: 4.5, servingSize: '2 Pieces (100g)', category: 'Snack' },
  { id: 'f-109', name: 'Makhana / Fox Nuts (Roasted)', calories: 120, protein: 3.5, carbs: 20, fat: 3, servingSize: '1 Bowl (30g)', category: 'Snack' },
  { id: 'f-110', name: 'Khakhra', calories: 110, protein: 3, carbs: 16, fat: 4, servingSize: '1 Piece (30g)', category: 'Snack' },
  { id: 'f-111', name: 'Veg Puff / Patties', calories: 270, protein: 5, carbs: 28, fat: 16, servingSize: '1 Piece (100g)', category: 'Snack' },
  { id: 'f-112', name: 'Egg Puff', calories: 310, protein: 10, carbs: 26, fat: 18, servingSize: '1 Piece (110g)', category: 'Snack' },
  { id: 'f-113', name: 'Murukku / Chakli', calories: 160, protein: 2, carbs: 18, fat: 9, servingSize: '3 Pieces (35g)', category: 'Snack' },
  { id: 'f-114', name: 'Banana Chips', calories: 150, protein: 1, carbs: 16, fat: 9, servingSize: 'Handful (30g)', category: 'Snack' },
  { id: 'f-115', name: 'Bhel Puri', calories: 210, protein: 4.5, carbs: 38, fat: 5, servingSize: '1 Plate (150g)', category: 'Snack' },
  { id: 'f-116', name: 'Pani Puri (6 pcs)', calories: 180, protein: 3, carbs: 28, fat: 6, servingSize: '6 Puri Plate', category: 'Snack' },
  { id: 'f-117', name: 'Vada Pav', calories: 290, protein: 6, carbs: 42, fat: 11, servingSize: '1 Piece (130g)', category: 'Snack' },
  { id: 'f-118', name: 'Pav Bhaji', calories: 400, protein: 9, carbs: 54, fat: 16, servingSize: '2 Pav + Bhaji (250g)', category: 'Snack' },

  // --- FAST FOOD / STREET FOOD ---
  { id: 'f-119', name: 'Veg Burger', calories: 320, protein: 9, carbs: 45, fat: 12, servingSize: '1 Burger (160g)', category: 'Fast Food' },
  { id: 'f-120', name: 'Chicken Burger', calories: 410, protein: 22, carbs: 42, fat: 18, servingSize: '1 Burger (180g)', category: 'Fast Food' },
  { id: 'f-121', name: 'Chicken Kathi Roll', calories: 380, protein: 22, carbs: 36, fat: 16, servingSize: '1 Roll (180g)', category: 'Fast Food' },
  { id: 'f-122', name: 'Paneer Kathi Roll', calories: 360, protein: 14, carbs: 38, fat: 17, servingSize: '1 Roll (180g)', category: 'Fast Food' },
  { id: 'f-123', name: 'Steamed Momos (Veg, 6 pcs)', calories: 210, protein: 5, carbs: 38, fat: 4, servingSize: '6 Pieces (150g)', category: 'Fast Food' },
  { id: 'f-124', name: 'Steamed Momos (Chicken, 6 pcs)', calories: 260, protein: 16, carbs: 34, fat: 6, servingSize: '6 Pieces (150g)', category: 'Fast Food' },
  { id: 'f-125', name: 'Veg Noodles / Chowmein', calories: 330, protein: 7, carbs: 52, fat: 11, servingSize: '1 Plate (220g)', category: 'Fast Food' },
  { id: 'f-126', name: 'French Fries', calories: 315, protein: 3.5, carbs: 41, fat: 15, servingSize: '1 Medium Pack (110g)', category: 'Fast Food' },
  { id: 'f-127', name: 'Margherita Pizza Slice', calories: 250, protein: 10, carbs: 30, fat: 10, servingSize: '1 Slice (100g)', category: 'Fast Food' },

  // --- LUNCH / DINNER CURRIES & DAALS ---
  { id: 'f-128', name: 'Fish Fry (South Style)', calories: 240, protein: 22, carbs: 4, fat: 15, servingSize: '1 Piece (120g)', category: 'Dinner' },
  { id: 'f-129', name: 'Mutton Curry / Gravy', calories: 360, protein: 24, carbs: 6, fat: 26, servingSize: '1 Katori (200g)', category: 'Dinner' },
  { id: 'f-130', name: 'Egg Curry (2 eggs)', calories: 240, protein: 14, carbs: 8, fat: 16, servingSize: '1 Katori (200g)', category: 'Dinner' },
  { id: 'f-131', name: 'Soya Bean Curry', calories: 210, protein: 18, carbs: 16, fat: 7, servingSize: '1 Katori (200g)', category: 'Lunch' },
  { id: 'f-132', name: 'Moong Dal Fry', calories: 140, protein: 7, carbs: 21, fat: 3.5, servingSize: '1 Katori (180g)', category: 'Lunch' },
  { id: 'f-133', name: 'Kadhi Pakora', calories: 230, protein: 6, carbs: 22, fat: 13, servingSize: '1 Katori (200g)', category: 'Lunch' },
  { id: 'f-134', name: 'Aloo Matar', calories: 150, protein: 4, carbs: 24, fat: 4.5, servingSize: '1 Katori (180g)', category: 'Lunch' },
  { id: 'f-135', name: 'Matar Paneer', calories: 260, protein: 10, carbs: 16, fat: 17, servingSize: '1 Katori (200g)', category: 'Lunch' },

  // --- SWEETS & DESSERTS ---
  { id: 'f-136', name: 'Gulab Jamun (1 pc)', calories: 150, protein: 2, carbs: 24, fat: 6, servingSize: '1 Piece (50g)', category: 'Snack' },
  { id: 'f-137', name: 'Rasgulla (1 pc)', calories: 120, protein: 2.5, carbs: 23, fat: 1.5, servingSize: '1 Piece (50g)', category: 'Snack' },
  { id: 'f-138', name: 'Kheer / Payasam', calories: 220, protein: 5, carbs: 34, fat: 7, servingSize: '1 Bowl (150g)', category: 'Snack' },
  { id: 'f-139', name: 'Jalebi', calories: 180, protein: 1, carbs: 32, fat: 5, servingSize: '2 Pieces (50g)', category: 'Snack' },
  { id: 'f-140', name: 'Halwa (Gajar / Sooji)', calories: 260, protein: 3.5, carbs: 38, fat: 11, servingSize: '1 Bowl (120g)', category: 'Snack' },

  // --- EXTRA COMMON HOUSEHOLD ITEMS ---
  { id: 'f-141', name: 'Full Cream Milk', calories: 150, protein: 8, carbs: 12, fat: 8, servingSize: '1 Glass (240ml)', category: 'Drink' },
  { id: 'f-142', name: 'Toned / Skim Milk', calories: 90, protein: 8, carbs: 12, fat: 1.5, servingSize: '1 Glass (240ml)', category: 'Drink' },
  { id: 'f-143', name: 'Curd / Dahi (Whole Milk)', calories: 120, protein: 5, carbs: 6, fat: 8, servingSize: '1 Bowl (150g)', category: 'Lunch' },
  { id: 'f-144', name: 'Homemade Butter (Makhan)', calories: 100, protein: 0.1, carbs: 0.1, fat: 11, servingSize: '1 tbsp (14g)', category: 'Snack' },
  { id: 'f-145', name: 'Ghee', calories: 120, protein: 0, carbs: 0, fat: 14, servingSize: '1 tbsp (14g)', category: 'Lunch' },
  { id: 'f-146', name: 'Coconut Chutney', calories: 60, protein: 1, carbs: 3, fat: 5, servingSize: '2 tbsp (30g)', category: 'South Indian' },
  { id: 'f-147', name: 'Tomato Garlic Chutney', calories: 35, protein: 0.5, carbs: 5, fat: 1.5, servingSize: '2 tbsp (30g)', category: 'South Indian' },
  { id: 'f-148', name: 'Mint Coriander Chutney', calories: 20, protein: 0.5, carbs: 3, fat: 0.5, servingSize: '2 tbsp (30g)', category: 'North Indian' },
  { id: 'f-149', name: 'Boiled Chana Salad', calories: 140, protein: 7, carbs: 22, fat: 2.5, servingSize: '1 Bowl (150g)', category: 'Snack' },
  { id: 'f-150', name: 'Corn Bhel / Boiled Sweet Corn', calories: 130, protein: 4, carbs: 26, fat: 2, servingSize: '1 Bowl (150g)', category: 'Snack' },
];
