import { workoutPlanner } from '../intelligence/workoutPlanner';
import { workoutService } from '../services/workoutService';
import { getPersona } from '../persona';
import { transformationIntelligenceEngine } from '../intelligence';
import { systemController } from '../system/systemController';
import { eventBus } from '../system/eventBus';
import { stateSynchronizer } from './stateSynchronizer';
import { WorkoutData } from '../types';

export interface WorkoutScreenData {
  todayWorkoutPlan: ReturnType<typeof workoutPlanner.generateTodayWorkout>;
  sessionType: string;
  targetFocus: string;
  exercises: {
    name: string;
    targetMuscle: string;
    sets: number;
    reps: string;
    tempo: string;
    restSeconds: number;
    rpeIntensity: string;
    notes: string;
  }[];
  estimatedDurationMins: number;
  coachNotes: string[];
  weakMusclePriority: string[];
  isCompletedToday: boolean;
}

/**
 * WorkoutConnector
 * Connects Workout Planner & Workout Service to deliver dynamic, AI-generated
 * workout routines and handle workout completion events.
 */
export class WorkoutConnector {
  /**
   * Retrieves today's live Workout Plan generated by Workout Planner without static fallbacks.
   */
  public getTodayWorkoutData(): WorkoutScreenData {
    const persona = getPersona();
    const intelState = transformationIntelligenceEngine.runFullTransformationLoop(1, 1);
    const plan = workoutPlanner.generateTodayWorkout(intelState.status.recoveryScore, 1, 1);

    const formattedExercises = plan.exercises.map((ex) => ({
      name: ex.name,
      targetMuscle: ex.targetMuscle,
      sets: ex.sets,
      reps: ex.reps,
      tempo: ex.tempo,
      restSeconds: ex.restSeconds,
      rpeIntensity: `RPE ${ex.targetRPE}`,
      notes: ex.notes || `Focus on controlled ${ex.tempo} tempo and strict tension.`,
    }));

    return {
      todayWorkoutPlan: plan,
      sessionType: plan.sessionType,
      targetFocus: plan.targetFocus,
      exercises: formattedExercises,
      estimatedDurationMins: plan.estimatedDurationMins,
      coachNotes: plan.trainingNotes,
      weakMusclePriority: persona.body?.weakAreas || ['Upper Chest', 'Rear Delts'],
      isCompletedToday: workoutService.getCompletedWorkouts().some((w) => w.date === new Date().toISOString().split('T')[0]),
    };
  }

  /**
   * Completes and logs a workout, executing the System Controller workout pipeline.
   */
  public async logCompletedWorkout(workoutData?: WorkoutData): Promise<void> {
    const sessionType = workoutData?.title || 'Hypertrophy Session';
    const durationMins = workoutData?.durationMinutes || 45;
    const setsCompleted = workoutData?.exercises?.reduce(
      (acc, ex) => acc + ex.sets.filter((s) => s.completed).length,
      0
    ) || 12;

    if (workoutData) {
      workoutService.saveCompletedWorkout(workoutData);
    }

    eventBus.emit('WORKOUT_COMPLETED', {
      sessionType,
      durationMins,
      setsCompleted,
      timestamp: new Date().toISOString(),
    });

    await systemController.runWorkoutPipeline({
      sessionType,
      durationMins,
      setsCompleted,
    });

    stateSynchronizer.notifySubscribers();
  }
}

export const workoutConnector = new WorkoutConnector();
