export interface LocalFoodItem {
  id: string;
  name: string;
  priceInr: number;
  calories: number;
  protein: number; // grams
  carbs: number; // grams
  fat: number; // grams
  mealType: 'Breakfast' | 'Lunch' | 'Dinner' | 'Snack' | 'Pre-workout' | 'Post-workout';
  workoutSuitability: 'Pre-workout' | 'Post-workout' | 'Rest Day' | 'All Day';
  budgetRating: number; // 1 to 5 (5 = cheapest / best budget value)
  proteinEfficiency: number; // g protein per ₹ INR
  satietyRating: number; // 1 to 5
  recoveryRating: number; // 1 to 5
  isWeekday: boolean;
  isWeekend: boolean;
  isPrimaryStaple: boolean; // True for daily staple menu items
  locationSource: string; // e.g. "SNS Gate Stall", "Saravanampatti Mess", "PG Room (Induction)", "Canteen"
  preparationConstraint: string; // e.g. "Requires Boiling on Induction", "Direct Purchase / Ready", "PG Mess"
  servingSize: string;
  category: 'South Indian' | 'Biryani & Rice' | 'Eggs & Chicken' | 'Vegetarian Protein' | 'Budget Snack' | 'Weekend Special';
}

/**
 * Hyper-local Saravanampatti (Coimbatore, TN) Food Database.
 * Calibrated specifically for a student near SNS College of Technology
 * with an Induction Stove (can only boil eggs), no fridge, no microwave,
 * and a ₹4500/month (~₹150/day) budget.
 */
export const LOCAL_FOOD_KNOWLEDGE_BASE: LocalFoodItem[] = [
  // --- PRIMARY DAILY STAPLES (Available Every Day) ---
  {
    id: 'loc-1',
    name: 'Egg Dosa',
    priceInr: 20,
    calories: 220,
    protein: 14,
    carbs: 22,
    fat: 9,
    mealType: 'Breakfast',
    workoutSuitability: 'Post-workout',
    budgetRating: 5,
    proteinEfficiency: 0.70, // 14g / ₹20
    satietyRating: 4,
    recoveryRating: 4,
    isWeekday: true,
    isWeekend: true,
    isPrimaryStaple: true,
    locationSource: 'SNS Gate Stall / Saravanampatti Mess',
    preparationConstraint: 'Direct Purchase / Ready to eat',
    servingSize: '1 Dosa',
    category: 'South Indian',
  },
  {
    id: 'loc-2',
    name: 'Egg Chapati',
    priceInr: 20,
    calories: 210,
    protein: 12,
    carbs: 22,
    fat: 8,
    mealType: 'Dinner',
    workoutSuitability: 'All Day',
    budgetRating: 5,
    proteinEfficiency: 0.60,
    satietyRating: 4,
    recoveryRating: 4,
    isWeekday: true,
    isWeekend: true,
    isPrimaryStaple: true,
    locationSource: 'Saravanampatti Mess / Tiffin Center',
    preparationConstraint: 'Direct Purchase / Ready to eat',
    servingSize: '1 Stuffed Chapati',
    category: 'South Indian',
  },
  {
    id: 'loc-3',
    name: 'Plain Dosa',
    priceInr: 15,
    calories: 140,
    protein: 4,
    carbs: 24,
    fat: 3.5,
    mealType: 'Breakfast',
    workoutSuitability: 'Pre-workout',
    budgetRating: 5,
    proteinEfficiency: 0.27,
    satietyRating: 3,
    recoveryRating: 2,
    isWeekday: true,
    isWeekend: true,
    isPrimaryStaple: true,
    locationSource: 'SNS College Canteen / Local Tiffin',
    preparationConstraint: 'Direct Purchase / Ready to eat',
    servingSize: '1 Medium Dosa',
    category: 'South Indian',
  },
  {
    id: 'loc-4',
    name: 'Plain Chapati',
    priceInr: 15,
    calories: 80,
    protein: 3,
    carbs: 15,
    fat: 0.5,
    mealType: 'Dinner',
    workoutSuitability: 'Pre-workout',
    budgetRating: 5,
    proteinEfficiency: 0.20,
    satietyRating: 3,
    recoveryRating: 2,
    isWeekday: true,
    isWeekend: true,
    isPrimaryStaple: true,
    locationSource: 'PG Mess / Local Tiffin Stall',
    preparationConstraint: 'Direct Purchase / Ready to eat',
    servingSize: '1 Phulka / Chapati',
    category: 'South Indian',
  },
  {
    id: 'loc-5',
    name: 'White Rice + Sambar',
    priceInr: 45,
    calories: 320,
    protein: 7,
    carbs: 62,
    fat: 4,
    mealType: 'Lunch',
    workoutSuitability: 'Pre-workout',
    budgetRating: 5,
    proteinEfficiency: 0.16,
    satietyRating: 5,
    recoveryRating: 3,
    isWeekday: true,
    isWeekend: true,
    isPrimaryStaple: true,
    locationSource: 'Saravanampatti Meals Mess / PG Mess',
    preparationConstraint: 'Direct Purchase / Ready to eat',
    servingSize: '1 Full Thali Bowl (250g)',
    category: 'South Indian',
  },
  {
    id: 'loc-6',
    name: 'Kuska (Plain Biryani Rice)',
    priceInr: 50,
    calories: 380,
    protein: 6,
    carbs: 58,
    fat: 14,
    mealType: 'Lunch',
    workoutSuitability: 'Pre-workout',
    budgetRating: 4,
    proteinEfficiency: 0.12,
    satietyRating: 4,
    recoveryRating: 2,
    isWeekday: true,
    isWeekend: true,
    isPrimaryStaple: true,
    locationSource: 'Saravanampatti Biryani Corner',
    preparationConstraint: 'Direct Purchase / Ready to eat',
    servingSize: '1 Plate (300g)',
    category: 'Biryani & Rice',
  },
  {
    id: 'loc-7',
    name: 'Egg Biryani (2 Eggs)',
    priceInr: 60,
    calories: 420,
    protein: 16,
    carbs: 56,
    fat: 15,
    mealType: 'Lunch',
    workoutSuitability: 'Post-workout',
    budgetRating: 5,
    proteinEfficiency: 0.27,
    satietyRating: 5,
    recoveryRating: 4,
    isWeekday: true,
    isWeekend: true,
    isPrimaryStaple: true,
    locationSource: 'SNS Gate Biryani Shop',
    preparationConstraint: 'Direct Purchase / Ready to eat',
    servingSize: '1 Plate (350g)',
    category: 'Biryani & Rice',
  },
  {
    id: 'loc-8',
    name: 'Chicken Biryani',
    priceInr: 100,
    calories: 520,
    protein: 26,
    carbs: 58,
    fat: 22,
    mealType: 'Lunch',
    workoutSuitability: 'Post-workout',
    budgetRating: 3,
    proteinEfficiency: 0.26,
    satietyRating: 5,
    recoveryRating: 4,
    isWeekday: true,
    isWeekend: true,
    isPrimaryStaple: true,
    locationSource: 'Local Saravanampatti Hotel',
    preparationConstraint: 'Direct Purchase / Ready to eat',
    servingSize: '1 Full Plate (400g)',
    category: 'Biryani & Rice',
  },

  // --- SECONDARY FOODS (Nearby Stores & Induction Boiling) ---
  {
    id: 'loc-9',
    name: 'Boiled Eggs (2 Whole Eggs)',
    priceInr: 14,
    calories: 150,
    protein: 12,
    carbs: 1,
    fat: 10,
    mealType: 'Post-workout',
    workoutSuitability: 'Post-workout',
    budgetRating: 5,
    proteinEfficiency: 0.86, // High efficiency!
    satietyRating: 4,
    recoveryRating: 5,
    isWeekday: true,
    isWeekend: true,
    isPrimaryStaple: false,
    locationSource: 'PG Room (Boiled on Induction Stove)',
    preparationConstraint: 'Requires Boiling on Induction (8 mins)',
    servingSize: '2 Eggs',
    category: 'Eggs & Chicken',
  },
  {
    id: 'loc-10',
    name: 'Boiled Eggs (4 Whole Eggs)',
    priceInr: 28,
    calories: 300,
    protein: 24,
    carbs: 2,
    fat: 20,
    mealType: 'Post-workout',
    workoutSuitability: 'Post-workout',
    budgetRating: 5,
    proteinEfficiency: 0.86,
    satietyRating: 5,
    recoveryRating: 5,
    isWeekday: true,
    isWeekend: true,
    isPrimaryStaple: false,
    locationSource: 'PG Room (Boiled on Induction Stove)',
    preparationConstraint: 'Requires Boiling on Induction (8 mins)',
    servingSize: '4 Eggs',
    category: 'Eggs & Chicken',
  },
  {
    id: 'loc-11',
    name: 'Bananas (2 Large Yellow Bananas)',
    priceInr: 10,
    calories: 180,
    protein: 2.2,
    carbs: 46,
    fat: 0.6,
    mealType: 'Pre-workout',
    workoutSuitability: 'Pre-workout',
    budgetRating: 5,
    proteinEfficiency: 0.22,
    satietyRating: 3,
    recoveryRating: 4,
    isWeekday: true,
    isWeekend: true,
    isPrimaryStaple: false,
    locationSource: 'Saravanampatti Fruit Cart',
    preparationConstraint: 'Direct Purchase / No Prep',
    servingSize: '2 Bananas',
    category: 'Budget Snack',
  },
  {
    id: 'loc-12',
    name: 'Soya Chunks (50g dry - Boiled)',
    priceInr: 10,
    calories: 170,
    protein: 26,
    carbs: 15,
    fat: 0.5,
    mealType: 'Snack',
    workoutSuitability: 'Post-workout',
    budgetRating: 5,
    proteinEfficiency: 2.60, // ABSOLUTE HIGHEST PROTEIN EFFICIENCY
    satietyRating: 5,
    recoveryRating: 5,
    isWeekday: true,
    isWeekend: true,
    isPrimaryStaple: false,
    locationSource: 'PG Room (Boiled on Induction Stove)',
    preparationConstraint: 'Requires Boiling on Induction (5 mins)',
    servingSize: '50g Dry / 150g Rehydrated',
    category: 'Vegetarian Protein',
  },
  {
    id: 'loc-13',
    name: 'Roasted Chana / Bhuna Chana (50g)',
    priceInr: 10,
    calories: 180,
    protein: 11,
    carbs: 28,
    fat: 3,
    mealType: 'Snack',
    workoutSuitability: 'All Day',
    budgetRating: 5,
    proteinEfficiency: 1.10,
    satietyRating: 4,
    recoveryRating: 3,
    isWeekday: true,
    isWeekend: true,
    isPrimaryStaple: false,
    locationSource: 'Saravanampatti Mini Mart',
    preparationConstraint: 'Direct Purchase / No Prep',
    servingSize: '50g Pack',
    category: 'Budget Snack',
  },
  {
    id: 'loc-14',
    name: 'Peanuts / Groundnuts (50g)',
    priceInr: 8,
    calories: 280,
    protein: 13,
    carbs: 8,
    fat: 24,
    mealType: 'Snack',
    workoutSuitability: 'Rest Day',
    budgetRating: 5,
    proteinEfficiency: 1.62,
    satietyRating: 5,
    recoveryRating: 3,
    isWeekday: true,
    isWeekend: true,
    isPrimaryStaple: false,
    locationSource: 'Saravanampatti Grocery / Store',
    preparationConstraint: 'Direct Purchase / No Prep',
    servingSize: '50g Handful',
    category: 'Budget Snack',
  },
  {
    id: 'loc-15',
    name: 'Curd / Dahi Pouch (200g)',
    priceInr: 20,
    calories: 120,
    protein: 7,
    carbs: 8,
    fat: 6,
    mealType: 'Lunch',
    workoutSuitability: 'All Day',
    budgetRating: 4,
    proteinEfficiency: 0.35,
    satietyRating: 3,
    recoveryRating: 4,
    isWeekday: true,
    isWeekend: true,
    isPrimaryStaple: false,
    locationSource: 'Saravanampatti Milk Dairy / Store',
    preparationConstraint: 'Direct Purchase / No Prep',
    servingSize: '200g Pouch',
    category: 'Vegetarian Protein',
  },
  {
    id: 'loc-16',
    name: 'Milk Packet (250ml)',
    priceInr: 13,
    calories: 150,
    protein: 8,
    carbs: 12,
    fat: 8,
    mealType: 'Snack',
    workoutSuitability: 'All Day',
    budgetRating: 4,
    proteinEfficiency: 0.61,
    satietyRating: 3,
    recoveryRating: 3,
    isWeekday: true,
    isWeekend: true,
    isPrimaryStaple: false,
    locationSource: 'Aavin / Dairy Booth',
    preparationConstraint: 'Direct Purchase / Warm on Induction (Optional)',
    servingSize: '1 Cup (250ml)',
    category: 'Vegetarian Protein',
  },
  {
    id: 'loc-17',
    name: 'Sprouts Mix Pack (100g)',
    priceInr: 25,
    calories: 120,
    protein: 9,
    carbs: 20,
    fat: 1,
    mealType: 'Snack',
    workoutSuitability: 'Rest Day',
    budgetRating: 4,
    proteinEfficiency: 0.36,
    satietyRating: 4,
    recoveryRating: 4,
    isWeekday: true,
    isWeekend: true,
    isPrimaryStaple: false,
    locationSource: 'Saravanampatti Fresh Vegetable Market',
    preparationConstraint: 'Direct Eat / Wash with water',
    servingSize: '100g Pack',
    category: 'Vegetarian Protein',
  },
  {
    id: 'loc-18',
    name: 'Boiled / Grilled Chicken Portion (150g)',
    priceInr: 80,
    calories: 240,
    protein: 38,
    carbs: 0,
    fat: 8,
    mealType: 'Dinner',
    workoutSuitability: 'Post-workout',
    budgetRating: 3,
    proteinEfficiency: 0.47,
    satietyRating: 5,
    recoveryRating: 5,
    isWeekday: true,
    isWeekend: true,
    isPrimaryStaple: false,
    locationSource: 'Saravanampatti Local Grill / Chicken Shop',
    preparationConstraint: 'Direct Purchase / Ready to eat',
    servingSize: '150g Meat',
    category: 'Eggs & Chicken',
  },

  // --- WEEKEND SPECIALS (Available Saturdays & Sundays) ---
  {
    id: 'loc-19',
    name: 'Mutton Biryani (Weekend Special)',
    priceInr: 180,
    calories: 620,
    protein: 28,
    carbs: 65,
    fat: 26,
    mealType: 'Lunch',
    workoutSuitability: 'Post-workout',
    budgetRating: 2,
    proteinEfficiency: 0.15,
    satietyRating: 5,
    recoveryRating: 3,
    isWeekday: false,
    isWeekend: true,
    isPrimaryStaple: false,
    locationSource: 'Saravanampatti Weekend Mess Special',
    preparationConstraint: 'Direct Purchase / Ready to eat',
    servingSize: '1 Full Plate (400g)',
    category: 'Weekend Special',
  },
  {
    id: 'loc-20',
    name: 'Chicken 65 / Dry Fry (150g)',
    priceInr: 90,
    calories: 340,
    protein: 22,
    carbs: 12,
    fat: 22,
    mealType: 'Snack',
    workoutSuitability: 'Post-workout',
    budgetRating: 3,
    proteinEfficiency: 0.24,
    satietyRating: 4,
    recoveryRating: 4,
    isWeekday: false,
    isWeekend: true,
    isPrimaryStaple: false,
    locationSource: 'SNS Gate Street Vendor',
    preparationConstraint: 'Direct Purchase / Ready to eat',
    servingSize: '150g Plate',
    category: 'Weekend Special',
  },
  {
    id: 'loc-21',
    name: 'Fish Fry (1 Piece Rohu/Katla)',
    priceInr: 80,
    calories: 220,
    protein: 20,
    carbs: 6,
    fat: 12,
    mealType: 'Dinner',
    workoutSuitability: 'Post-workout',
    budgetRating: 3,
    proteinEfficiency: 0.25,
    satietyRating: 4,
    recoveryRating: 4,
    isWeekday: false,
    isWeekend: true,
    isPrimaryStaple: false,
    locationSource: 'Saravanampatti Fish Stall',
    preparationConstraint: 'Direct Purchase / Ready to eat',
    servingSize: '1 Large Fried Piece',
    category: 'Weekend Special',
  },
  {
    id: 'loc-22',
    name: 'Parotta + Chicken Gravy (2 Parottas)',
    priceInr: 60,
    calories: 480,
    protein: 18,
    carbs: 58,
    fat: 20,
    mealType: 'Dinner',
    workoutSuitability: 'Rest Day',
    budgetRating: 4,
    proteinEfficiency: 0.30,
    satietyRating: 5,
    recoveryRating: 3,
    isWeekday: false,
    isWeekend: true,
    isPrimaryStaple: false,
    locationSource: 'Local Saravanampatti Night Tiffin Stall',
    preparationConstraint: 'Direct Purchase / Ready to eat',
    servingSize: '2 Parottas + Gravy',
    category: 'Weekend Special',
  },
];

/**
 * Utility function to filter local foods by current day (Weekday vs Weekend).
 */
export function getAvailableLocalFoods(isWeekendOverride?: boolean): LocalFoodItem[] {
  const isWeekend = isWeekendOverride !== undefined 
    ? isWeekendOverride 
    : (new Date().getDay() === 0 || new Date().getDay() === 6);

  return LOCAL_FOOD_KNOWLEDGE_BASE.filter(item => {
    if (isWeekend) return item.isWeekend;
    return item.isWeekday;
  });
}
